import { db, machinesTable, adminSettingsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

const SEED_MACHINES = [
  {
    name: "Rolling Shutter Machine",
    model: "RS-5000",
    category: "Rolling Shutter",
    capacity: "2-4 tons/hr",
    power: "15 kW",
    speed: "25 m/min",
    price: "₹12-18 Lakhs",
    description: "High-speed rolling shutter patti making machine with automatic stacking",
    weight: "3.5 tons",
    dimensions: "12m x 1.2m x 1.5m",
    rollers: "18 stages",
    color: "#1A56DB",
    detailedDescription: "The RS-5000 Rolling Shutter Machine is our flagship roll forming system designed for high-volume production of rolling shutter patti (slats). Built with precision-hardened steel rollers and powered by a 15 kW motor, this machine delivers consistent quality at 25 meters per minute. The integrated PLC control system with touchscreen HMI allows operators to set exact dimensions, count pieces, and monitor production in real-time. The automatic stacking system eliminates manual handling, reducing labor costs by up to 60%. Ideal for rolling shutter manufacturers looking to scale their production capacity with minimal downtime.",
    warranty: "2 Years Comprehensive + 5 Years Roller",
    tags: ["High Speed", "Auto Stack", "ISO Certified"],
    specs: [
      { label: "Production Capacity", value: "2-4 tons/hr" },
      { label: "Machine Speed", value: "25 m/min" },
      { label: "Motor Power", value: "15 kW" },
      { label: "Total Weight", value: "3.5 tons" },
      { label: "Dimensions", value: "12m x 1.2m x 1.5m" },
      { label: "Roller Stages", value: "18 stages" },
      { label: "Material Thickness", value: "0.3-0.8 mm" },
      { label: "Material Width", value: "90 mm" },
    ],
    features: [
      "PLC control system with touchscreen HMI",
      "Automatic stacking & counting system",
      "Hydraulic decoiler with auto feeder",
      "Flying shear cutting with servo motor",
      "Remote diagnostics capability",
      "CE certified design",
    ],
    applications: [
      "Rolling shutter slat manufacturing",
      "Industrial shutter doors",
      "Commercial shop shutters",
      "Garage door panels",
      "Security shutters",
    ],
    accessories: [
      "Hydraulic Decoiler (5 Ton)",
      "Automatic Stacking Table",
      "Flying Shear Cutter",
      "PLC Control Panel with HMI",
      "Spare Roller Set",
      "Lubrication Kit",
      "Safety Guards & Sensors",
    ],
    images: [
      { id: "1-1", url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop", label: "Full Machine View", type: "front" },
      { id: "1-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Roller Assembly", type: "detail" },
      { id: "1-3", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "PLC Control Panel", type: "panel" },
      { id: "1-4", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Output Product", type: "output" },
      { id: "1-5", url: "https://images.unsplash.com/photo-1537462715828-7f190ad5cd9f?w=800&h=600&fit=crop", label: "Production Line", type: "process" },
    ],
    videos: [
      { id: "v1-1", title: "RS-5000 Live Demo", duration: "3:45", thumbnail: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
      { id: "v1-2", title: "Installation Guide", duration: "8:20", thumbnail: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "installation" },
      { id: "v1-3", title: "Output Sample", duration: "1:30", thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "output" },
    ],
  },
  {
    name: "T-Grid Ceiling Machine",
    model: "TG-3000",
    category: "False Ceiling",
    capacity: "1.5-2 tons/hr",
    power: "11 kW",
    speed: "20 m/min",
    price: "₹8-12 Lakhs",
    description: "T-Grid false ceiling section making machine for commercial projects",
    color: "#10B981",
    detailedDescription: "The TG-3000 T-Grid Ceiling Machine is a precision roll forming system designed for manufacturing T-Grid false ceiling sections used in commercial buildings, offices, and hospitals. The machine produces both main tee and cross tee profiles with exceptional dimensional accuracy. Its compact design makes it suitable for small to medium-scale manufacturing units while maintaining production quality comparable to larger systems. The low-noise operation makes it ideal for urban manufacturing setups.",
    warranty: "1 Year Comprehensive + 3 Years Roller",
    tags: ["Precision", "Low Noise"],
    specs: [
      { label: "Production Capacity", value: "1.5-2 tons/hr" },
      { label: "Machine Speed", value: "20 m/min" },
      { label: "Motor Power", value: "11 kW" },
      { label: "Material Thickness", value: "0.25-0.5 mm" },
      { label: "Profile Width", value: "38 mm / 24 mm" },
    ],
    features: [
      "High precision roller dies",
      "Auto cutting to length",
      "Compact design",
      "Low maintenance",
      "Energy efficient motor",
    ],
    applications: [
      "Commercial building ceilings",
      "Office partition systems",
      "Hospital & cleanroom ceilings",
      "Shopping mall interiors",
      "Modular ceiling panels",
    ],
    accessories: [
      "Manual Decoiler (3 Ton)",
      "Auto Cutter Unit",
      "Spare Die Set (Main Tee + Cross Tee)",
      "Punch Unit",
      "Lubricant System",
    ],
    images: [
      { id: "2-1", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "Machine Overview", type: "front" },
      { id: "2-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Forming Station", type: "detail" },
      { id: "2-3", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "T-Grid Output", type: "output" },
      { id: "2-4", url: "https://images.unsplash.com/photo-1537462715828-7f190ad5cd9f?w=800&h=600&fit=crop", label: "Control System", type: "panel" },
    ],
    videos: [
      { id: "v2-1", title: "TG-3000 Production Demo", duration: "2:50", thumbnail: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
      { id: "v2-2", title: "Maintenance Tips", duration: "5:15", thumbnail: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "maintenance" },
    ],
  },
  {
    name: "C-Purlin Machine",
    model: "CP-8000",
    category: "Structural",
    capacity: "3-5 tons/hr",
    power: "22 kW",
    speed: "30 m/min",
    price: "₹20-28 Lakhs",
    description: "Heavy-duty C-Purlin roll forming machine for structural applications",
    color: "#8B5CF6",
    detailedDescription: "The CP-8000 C-Purlin Machine is a heavy-duty roll forming system engineered for manufacturing C-shaped structural purlins used in pre-engineered buildings (PEB), warehouses, and industrial sheds. With automatic size changeover via PLC control, operators can switch between C100 to C300 profiles without manual roller adjustments, dramatically reducing downtime. The machine handles material thickness up to 3.0 mm, making it suitable for both light and heavy structural applications. The integrated hydraulic post-cut system ensures clean, burr-free cuts at full production speed.",
    warranty: "2 Years Comprehensive + 5 Years Roller",
    tags: ["Heavy Duty", "PLC Control", "Auto Change"],
    specs: [
      { label: "Production Capacity", value: "3-5 tons/hr" },
      { label: "Machine Speed", value: "30 m/min" },
      { label: "Motor Power", value: "22 kW" },
      { label: "Profile Range", value: "C100 to C300" },
      { label: "Material Thickness", value: "1.5-3.0 mm" },
    ],
    features: [
      "PLC + servo motor control",
      "Automatic size changeover",
      "Hydraulic post-cut system",
      "Heavy-duty construction",
      "Built-in straightener",
    ],
    applications: [
      "Pre-engineered buildings (PEB)",
      "Industrial warehouses",
      "Factory roofing structures",
      "Agricultural storage sheds",
      "Commercial building frames",
    ],
    accessories: [
      "Hydraulic Decoiler (8 Ton)",
      "Auto Size Changeover System",
      "Hydraulic Post-Cut System",
      "PLC Control with Servo",
      "Straightener Unit",
      "Spare Roller Set (C150)",
      "Run-Out Table (6m)",
    ],
    images: [
      { id: "3-1", url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop", label: "CP-8000 Full View", type: "front" },
      { id: "3-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Roller Assembly Detail", type: "detail" },
      { id: "3-3", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "PLC Touch Panel", type: "panel" },
      { id: "3-4", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "C-Purlin Output", type: "output" },
      { id: "3-5", url: "https://images.unsplash.com/photo-1537462715828-7f190ad5cd9f?w=800&h=600&fit=crop", label: "Side View", type: "side" },
    ],
    videos: [
      { id: "v3-1", title: "CP-8000 Auto Changeover Demo", duration: "4:10", thumbnail: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
      { id: "v3-2", title: "Installation & Setup", duration: "12:00", thumbnail: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "installation" },
    ],
  },
  {
    name: "Trapezoidal Sheet Machine",
    model: "TR-6000",
    category: "Roofing & Cladding",
    capacity: "4-6 tons/hr",
    power: "18 kW",
    speed: "35 m/min",
    price: "₹15-22 Lakhs",
    description: "Trapezoidal roofing sheet forming machine with auto cutter",
    color: "#64748B",
    detailedDescription: "The TR-6000 Trapezoidal Sheet Machine produces high-quality trapezoidal roofing and cladding sheets used in industrial buildings, warehouses, and commercial structures. Operating at 35 m/min with a servo-driven flying cut system, it delivers exceptional throughput while maintaining precise sheet lengths. The machine accepts coil widths from 1000-1250 mm and can handle pre-painted (color-coated) steel coils, producing ready-to-install roofing sheets. The auto stacker system allows for continuous operation without manual intervention.",
    warranty: "2 Years Comprehensive + 3 Years Roller",
    tags: ["High Speed", "Auto Cut"],
    specs: [
      { label: "Production Capacity", value: "4-6 tons/hr" },
      { label: "Machine Speed", value: "35 m/min" },
      { label: "Motor Power", value: "18 kW" },
      { label: "Sheet Width", value: "1000-1250 mm" },
      { label: "Material Thickness", value: "0.3-0.8 mm" },
    ],
    features: [
      "Fully automatic operation",
      "Servo driven flying cut",
      "Touch screen HMI",
      "Auto stacker system",
    ],
    applications: [
      "Industrial roofing",
      "Warehouse cladding",
      "Commercial building facades",
      "Cold storage panels",
      "Residential metal roofing",
    ],
    accessories: [
      "Hydraulic Decoiler (6 Ton)",
      "Servo Flying Cut System",
      "Auto Stacker",
      "Touch Screen HMI Panel",
      "Coil Car (Optional)",
    ],
    images: [
      { id: "4-1", url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop", label: "TR-6000 Overview", type: "front" },
      { id: "4-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Forming Rollers", type: "detail" },
      { id: "4-3", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Roofing Sheet Output", type: "output" },
    ],
    videos: [
      { id: "v4-1", title: "TR-6000 High-Speed Demo", duration: "2:30", thumbnail: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
    ],
  },
  {
    name: "Door Frame Machine",
    model: "DF-4000",
    category: "Door & Window",
    capacity: "1-2 tons/hr",
    power: "9 kW",
    speed: "15 m/min",
    price: "₹6-10 Lakhs",
    description: "Steel door frame roll forming machine with punch holes",
    color: "#F59E0B",
    detailedDescription: "The DF-4000 Door Frame Machine is a compact, energy-efficient roll forming system designed specifically for manufacturing steel door frames. It features an integrated punch and notch system that creates hinge holes, lock slots, and rubber channel grooves in a single pass, eliminating secondary operations. The machine's small footprint makes it perfect for workshops with limited space, while its 9 kW motor keeps electricity costs low. Suitable for both residential and commercial door frame production.",
    warranty: "1 Year Comprehensive + 3 Years Roller",
    tags: ["Compact", "Energy Saver"],
    specs: [
      { label: "Production Capacity", value: "1-2 tons/hr" },
      { label: "Machine Speed", value: "15 m/min" },
      { label: "Motor Power", value: "9 kW" },
      { label: "Frame Width", value: "75-100 mm" },
      { label: "Material Thickness", value: "0.8-1.5 mm" },
    ],
    features: [
      "Automatic punch & notch",
      "Compact footprint",
      "Quick changeover",
      "Energy efficient drive",
    ],
    applications: [
      "Residential steel door frames",
      "Commercial door frames",
      "Window frames",
      "Security door frames",
      "Fire-rated door frames",
    ],
    accessories: [
      "Manual Decoiler (3 Ton)",
      "Punch & Notch Unit",
      "Cutter Assembly",
      "Spare Punch Dies",
      "Safety Guard Set",
    ],
    images: [
      { id: "5-1", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "DF-4000 Machine", type: "front" },
      { id: "5-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Punch Assembly", type: "detail" },
      { id: "5-3", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Door Frame Output", type: "output" },
    ],
    videos: [
      { id: "v5-1", title: "DF-4000 Working Demo", duration: "3:00", thumbnail: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
    ],
  },
  {
    name: "Solar Channel Machine",
    model: "SC-2000",
    category: "Solar & Infrastructure",
    capacity: "2-3 tons/hr",
    power: "13 kW",
    speed: "22 m/min",
    price: "₹10-16 Lakhs",
    description: "Solar mounting structure channel forming machine for renewable energy",
    color: "#0EA5E9",
    detailedDescription: "The SC-2000 Solar Channel Machine is designed for the rapidly growing solar energy sector. It produces strut channels and mounting rails used in solar panel installation systems — both rooftop and ground-mounted. The machine offers multi-profile capability, producing 41x41 mm and 41x21 mm channels from a single setup with quick changeover. PLC-controlled production ensures consistent slot patterns for module clamps. The corrosion-resistant hardened steel rollers provide extended service life even when processing galvanized and pre-galvanized steel coils.",
    warranty: "2 Years Comprehensive + 3 Years Roller",
    tags: ["Solar Ready", "PLC"],
    specs: [
      { label: "Production Capacity", value: "2-3 tons/hr" },
      { label: "Machine Speed", value: "22 m/min" },
      { label: "Motor Power", value: "13 kW" },
      { label: "Channel Size", value: "41x41 / 41x21 mm" },
      { label: "Material Thickness", value: "1.0-2.5 mm" },
    ],
    features: [
      "Solar panel mounting ready",
      "PLC controlled production",
      "Multi-profile capability",
      "Corrosion resistant rollers",
    ],
    applications: [
      "Rooftop solar panel mounting",
      "Ground-mounted solar arrays",
      "Solar carport structures",
      "Cable tray systems",
      "Electrical strut channels",
    ],
    accessories: [
      "Hydraulic Decoiler (5 Ton)",
      "PLC Control System",
      "Multi-Profile Die Set",
      "Auto Slot Punching Unit",
      "Corrosion-Resistant Rollers",
    ],
    images: [
      { id: "6-1", url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop", label: "SC-2000 Machine", type: "front" },
      { id: "6-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Channel Rollers", type: "detail" },
      { id: "6-3", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Solar Channel Output", type: "output" },
      { id: "6-4", url: "https://images.unsplash.com/photo-1537462715828-7f190ad5cd9f?w=800&h=600&fit=crop", label: "PLC Panel", type: "panel" },
    ],
    videos: [
      { id: "v6-1", title: "SC-2000 Production Line", duration: "4:30", thumbnail: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
      { id: "v6-2", title: "Solar Channel Applications", duration: "2:15", thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "output" },
    ],
  },
  {
    name: "Stud & Track Machine",
    model: "ST-3500",
    category: "Drywall & Partition",
    capacity: "1.5-2.5 tons/hr",
    power: "10 kW",
    speed: "18 m/min",
    price: "₹7-11 Lakhs",
    description: "Light gauge steel stud and track forming machine for drywall partitions",
    color: "#EF4444",
    detailedDescription: "The ST-3500 Stud & Track Machine is a versatile light gauge steel framing system designed for the booming drywall and partition industry. It produces both studs (C-shaped) and tracks (U-shaped) from a single machine with quick profile changeover — typically under 15 minutes. Optimized for light gauge steel (0.45-1.2 mm), it delivers clean, accurate profiles suitable for direct use in drywall framing without any post-processing. The low-noise operation and compact design make it ideal for urban manufacturing facilities.",
    warranty: "1 Year Comprehensive + 3 Years Roller",
    tags: ["Lightweight", "Fast Setup"],
    specs: [
      { label: "Production Capacity", value: "1.5-2.5 tons/hr" },
      { label: "Machine Speed", value: "18 m/min" },
      { label: "Motor Power", value: "10 kW" },
      { label: "Stud Width", value: "50-150 mm" },
      { label: "Material Thickness", value: "0.45-1.2 mm" },
    ],
    features: [
      "Dual profile (stud + track)",
      "Quick profile changeover",
      "Light gauge optimized",
      "Low noise operation",
    ],
    applications: [
      "Drywall partition framing",
      "False ceiling support",
      "Interior wall framing",
      "Modular construction",
      "Prefab building components",
    ],
    accessories: [
      "Manual Decoiler (3 Ton)",
      "Dual Profile Die Set",
      "Auto Cutter",
      "Changeover Tool Kit",
      "Spare Roller Set",
    ],
    images: [
      { id: "7-1", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "ST-3500 Machine", type: "front" },
      { id: "7-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Profile Detail", type: "detail" },
      { id: "7-3", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Stud & Track Output", type: "output" },
    ],
    videos: [
      { id: "v7-1", title: "ST-3500 Dual Profile Demo", duration: "3:20", thumbnail: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
    ],
  },
  {
    name: "Z-Purlin Machine",
    model: "ZP-7000",
    category: "Structural",
    capacity: "3-4 tons/hr",
    power: "20 kW",
    speed: "28 m/min",
    price: "₹18-25 Lakhs",
    description: "Heavy-duty Z-Purlin roll forming machine with adjustable size",
    color: "#8B5CF6",
    detailedDescription: "The ZP-7000 Z-Purlin Machine is a heavy-duty roll forming system designed for manufacturing Z-shaped structural purlins. The key advantage of this machine is its adjustable profile width — operators can change the web depth from Z100 to Z250 without replacing rollers, using the PLC-controlled adjustment system. This flexibility makes it ideal for job-shop environments serving multiple customers with varying purlin specifications. The hydraulic cut system handles material up to 3.0 mm thickness with clean, precise cuts. Built-in memory storage saves up to 50 profile settings for instant recall.",
    warranty: "2 Years Comprehensive + 5 Years Roller",
    tags: ["Adjustable", "Heavy Duty"],
    specs: [
      { label: "Production Capacity", value: "3-4 tons/hr" },
      { label: "Machine Speed", value: "28 m/min" },
      { label: "Motor Power", value: "20 kW" },
      { label: "Profile Range", value: "Z100 to Z250" },
      { label: "Material Thickness", value: "1.5-3.0 mm" },
    ],
    features: [
      "Adjustable profile width",
      "Heavy-duty roller design",
      "Hydraulic cut system",
      "PLC with memory storage",
    ],
    applications: [
      "Pre-engineered buildings",
      "Industrial shed roofing",
      "Warehouse structures",
      "Cold storage facilities",
      "Mezzanine floor supports",
    ],
    accessories: [
      "Hydraulic Decoiler (8 Ton)",
      "Adjustable Profile System",
      "Hydraulic Cut Station",
      "PLC with Memory (50 Profiles)",
      "Run-Out Table (6m)",
      "Spare Roller Set (Z150)",
    ],
    images: [
      { id: "8-1", url: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=800&h=600&fit=crop", label: "ZP-7000 Full Setup", type: "front" },
      { id: "8-2", url: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&h=600&fit=crop", label: "Adjustable Rollers", type: "detail" },
      { id: "8-3", url: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop", label: "Control Panel", type: "panel" },
      { id: "8-4", url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop", label: "Z-Purlin Output", type: "output" },
    ],
    videos: [
      { id: "v8-1", title: "ZP-7000 Size Adjustment Demo", duration: "5:00", thumbnail: "https://images.unsplash.com/photo-1565043666747-69f6646db940?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "demo" },
      { id: "v8-2", title: "Maintenance Guide", duration: "7:30", thumbnail: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=400&h=225&fit=crop", youtubeId: "dQw4w9WgXcQ", type: "maintenance" },
    ],
  },
  {
    name: "SAI Roll Forming Machine",
    model: "SAI-4.5",
    category: "Rolling Shutter",
    capacity: "2-3 tons/hr",
    power: "12 kW",
    speed: "20 m/min",
    price: "₹10-15 Lakhs",
    description: "SAI series compact roll forming machine for rolling shutter profiles",
    color: "#1A56DB",
    warranty: "2 Years Comprehensive",
    tags: ["SAI Series", "Compact"],
    specs: [
      { label: "Production Capacity", value: "2-3 tons/hr" },
      { label: "Machine Speed", value: "20 m/min" },
      { label: "Motor Power", value: "12 kW" },
    ],
    features: ["Compact design", "PLC control", "Auto cut"],
    applications: ["Rolling shutter manufacturing"],
    accessories: ["Decoiler", "Control Panel"],
    images: [],
    videos: [],
  },
  {
    name: "SAI Roll Forming Machine",
    model: "SAI-5.0",
    category: "Rolling Shutter",
    capacity: "3-4 tons/hr",
    power: "15 kW",
    speed: "25 m/min",
    price: "₹14-20 Lakhs",
    description: "SAI series mid-range roll forming machine with enhanced capacity",
    color: "#1A56DB",
    warranty: "2 Years Comprehensive",
    tags: ["SAI Series", "Mid-Range"],
    specs: [
      { label: "Production Capacity", value: "3-4 tons/hr" },
      { label: "Machine Speed", value: "25 m/min" },
      { label: "Motor Power", value: "15 kW" },
    ],
    features: ["Enhanced capacity", "PLC control", "Auto cut", "Servo motor"],
    applications: ["Rolling shutter manufacturing", "Industrial shutters"],
    accessories: ["Hydraulic Decoiler", "Control Panel", "Stacking Table"],
    images: [],
    videos: [],
  },
  {
    name: "SAI Roll Forming Machine",
    model: "SAI-6.0",
    category: "Rolling Shutter",
    capacity: "4-6 tons/hr",
    power: "18 kW",
    speed: "30 m/min",
    price: "₹18-25 Lakhs",
    description: "SAI series high-capacity roll forming machine for large-scale production",
    color: "#1A56DB",
    warranty: "2 Years Comprehensive + 5 Years Roller",
    tags: ["SAI Series", "High Capacity"],
    specs: [
      { label: "Production Capacity", value: "4-6 tons/hr" },
      { label: "Machine Speed", value: "30 m/min" },
      { label: "Motor Power", value: "18 kW" },
    ],
    features: ["High capacity", "PLC control", "Auto cut", "Servo motor", "Auto stacker"],
    applications: ["Rolling shutter manufacturing", "Industrial shutters", "Large-scale production"],
    accessories: ["Hydraulic Decoiler (8 Ton)", "Control Panel", "Stacking Table", "Flying Shear"],
    images: [],
    videos: [],
  },
];

async function seed() {
  console.log("Seeding machines...");

  const existingMachines = await db.select().from(machinesTable);
  if (existingMachines.length > 0) {
    console.log(`Database already has ${existingMachines.length} machines. Skipping seed.`);
    return;
  }

  for (const machineData of SEED_MACHINES) {
    const [machine] = await db.insert(machinesTable).values(machineData).returning();
    await db.insert(adminSettingsTable).values({ machineId: machine.id });
    console.log(`  Seeded: ${machine.name} (${machine.model})`);
  }

  console.log(`Seeded ${SEED_MACHINES.length} machines with admin settings.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
